export interface IDataverseWeatherData {
  _createdby_value: string;
  _createdonbehalfby_value: any | null;
  _modifiedby_value: string;
  _modifiedonbehalfby_value: any | null;
  _ownerid_value: string;
  _owningbusinessunit_value: string;
  _owningteam_value: any | null;
  _owninguser_value: string;
  cr4cc_alert_level: any | null;
  cr4cc_app_uptime: number;
  cr4cc_bar_absolute: any | null;
  cr4cc_bar_offset: any | null;
  cr4cc_bar_sea_level: any | null;
  cr4cc_bar_trend: any | null;
  cr4cc_battery_condition: number;
  cr4cc_battery_current: number;
  cr4cc_battery_cycle_count: number;
  cr4cc_battery_percent: number;
  cr4cc_battery_status: number;
  cr4cc_battery_status_text: any | null;
  cr4cc_battery_temp: number;
  cr4cc_battery_voltage: number;
  cr4cc_bgn: any | null;
  cr4cc_bootloader_version: number;
  cr4cc_cdd_day: number;
  cr4cc_charger_plugged: number;
  cr4cc_clock_source: number;
  cr4cc_comfort_index: any | null;
  cr4cc_connection_uptime: number;
  cr4cc_console_api_level: number;
  cr4cc_console_os_version: string;
  cr4cc_console_radio_version: string;
  cr4cc_console_sw_version: string;
  cr4cc_crc_errors_day: number;
  cr4cc_created_by: any | null;
  cr4cc_data_age_minutes: any | null;
  cr4cc_data_quality_score: any | null;
  cr4cc_database_kilobytes: number;
  cr4cc_dew_point: number;
  cr4cc_dew_point_celsius: number;
  cr4cc_dew_point_in: any | null;
  cr4cc_display_summary: any | null;
  cr4cc_dns_type_used: any | null;
  cr4cc_et_day: number;
  cr4cc_et_month: number;
  cr4cc_et_year: number;
  cr4cc_free_mem: number;
  cr4cc_freq_error_current: number;
  cr4cc_freq_error_total: number;
  cr4cc_freq_index: number;
  cr4cc_gnss_sip_tx_id: number;
  cr4cc_hdd_day: number;
  cr4cc_health_version: number;
  cr4cc_heat_index: number;
  cr4cc_heat_index_celsius: number;
  cr4cc_heat_index_in: any | null;
  cr4cc_hour_bucket: any | null;
  cr4cc_hum: number;
  cr4cc_hum_in: any | null;
  cr4cc_import_batch_id: any | null;
  cr4cc_internal_free_space: number;
  cr4cc_ip_address_type: any | null;
  cr4cc_ip_v4_address: string;
  cr4cc_ip_v4_gateway: string;
  cr4cc_ip_v4_netmask: string;
  cr4cc_is_current_reading: boolean;
  cr4cc_json_payload: any | null;
  cr4cc_last_packet_received_timestamp: number;
  cr4cc_link_uptime: number;
  cr4cc_local_api_queries: any | null;
  cr4cc_mobile_summary: any | null;
  cr4cc_os_uptime: number;
  cr4cc_packets_missed_day: number;
  cr4cc_packets_missed_streak: number;
  cr4cc_packets_missed_streak_hi_day: number;
  cr4cc_packets_received_day: number;
  cr4cc_packets_received_streak: number;
  cr4cc_packets_received_streak_hi_day: number;
  cr4cc_pressure_hpa: number;
  cr4cc_pressure_trend_description: any | null;
  cr4cc_queue_kilobytes: number;
  cr4cc_rain_rate_hi_clicks: number;
  cr4cc_rain_rate_hi_in: number;
  cr4cc_rain_rate_hi_last_15_min_clicks: number;
  cr4cc_rain_rate_hi_last_15_min_in: number;
  cr4cc_rain_rate_hi_last_15_min_mm: number;
  cr4cc_rain_rate_hi_mm: number;
  cr4cc_rain_rate_last_clicks: number;
  cr4cc_rain_rate_last_in: number;
  cr4cc_rain_rate_last_mm: number;
  cr4cc_rain_size: number;
  cr4cc_rain_storm_current_clicks: number;
  cr4cc_rain_storm_current_in: number;
  cr4cc_rain_storm_current_mm: number;
  cr4cc_rain_storm_last_clicks: number;
  cr4cc_rain_storm_last_end_at: number;
  cr4cc_rain_storm_last_in: number;
  cr4cc_rain_storm_last_mm: number;
  cr4cc_rain_storm_last_start_at: number;
  cr4cc_rainfall_day_clicks: number;
  cr4cc_rainfall_day_in: number;
  cr4cc_rainfall_day_mm: number;
  cr4cc_rainfall_last_15_min_clicks: number;
  cr4cc_rainfall_last_15_min_in: number;
  cr4cc_rainfall_last_15_min_mm: number;
  cr4cc_rainfall_last_24_hr_clicks: number;
  cr4cc_rainfall_last_24_hr_in: number;
  cr4cc_rainfall_last_24_hr_mm: number;
  cr4cc_rainfall_last_60_min_clicks: number;
  cr4cc_rainfall_last_60_min_in: number;
  cr4cc_rainfall_last_60_min_mm: number;
  cr4cc_rainfall_month_clicks: number;
  cr4cc_rainfall_month_in: number;
  cr4cc_rainfall_month_mm: number;
  cr4cc_rainfall_status: any | null;
  cr4cc_rainfall_year_clicks: number;
  cr4cc_rainfall_year_in: number;
  cr4cc_rainfall_year_mm: number;
  cr4cc_reception_day: number;
  cr4cc_record_id: string;
  cr4cc_resyncs_day: number;
  cr4cc_rssi_last: number;
  cr4cc_rx_kilobytes: number;
  cr4cc_rx_state: number;
  cr4cc_solar_energy_day: number;
  cr4cc_solar_panel_volt: number;
  cr4cc_solar_rad: any | null;
  cr4cc_spars_rpm: any | null;
  cr4cc_spars_volt: any | null;
  cr4cc_station_health_status: any | null;
  cr4cc_station_id: string;
  cr4cc_supercap_volt: number;
  cr4cc_system_free_space: number;
  cr4cc_temp: number;
  cr4cc_temp_celsius: number;
  cr4cc_temp_in: any | null;
  cr4cc_thsw_index: any | null;
  cr4cc_thw_index: number;
  cr4cc_track_name: string;
  cr4cc_trans_battery_flag: number;
  cr4cc_trans_battery_volt: number;
  cr4cc_ts: number;
  cr4cc_tx_id: number;
  cr4cc_tx_kilobytes: number;
  cr4cc_tz_offset: number;
  cr4cc_uv_dose_day: number;
  cr4cc_uv_index: any | null;
  cr4cc_wbgt: any | null;
  cr4cc_wbgt_in: any | null;
  cr4cc_weather_icon: any | null;
  cr4cc_weatherdataid: string;
  cr4cc_wet_bulb: number;
  cr4cc_wet_bulb_in: any | null;
  cr4cc_wifi_rssi: number;
  cr4cc_wind_chill: number;
  cr4cc_wind_description: any | null;
  cr4cc_wind_dir_at_hi_speed_last_10_min: number;
  cr4cc_wind_dir_at_hi_speed_last_2_min: number;
  cr4cc_wind_dir_last: number;
  cr4cc_wind_dir_scalar_avg_last_10_min: number;
  cr4cc_wind_dir_scalar_avg_last_1_min: number;
  cr4cc_wind_dir_scalar_avg_last_2_min: number;
  cr4cc_wind_direction_cardinal: any | null;
  cr4cc_wind_run_day: number;
  cr4cc_wind_speed_avg_last_10_min: number;
  cr4cc_wind_speed_avg_last_1_min: number;
  cr4cc_wind_speed_avg_last_2_min: number;
  cr4cc_wind_speed_hi_kmh: number;
  cr4cc_wind_speed_hi_last_10_min: number;
  cr4cc_wind_speed_hi_last_2_min: number;
  cr4cc_wind_speed_kmh: number;
  cr4cc_wind_speed_last: number;
  createdon: string;
  importsequencenumber: any | null;
  modifiedon: string;
  overriddencreatedon: any | null;
  statecode: number;
  statuscode: number;
  timezoneruleversionnumber: any | null;
  utcconversiontimezonecode: any | null;
  versionnumber: number;
}