
require("./RaceMeetings.module.css");
const styles = {
  raceMeetings: 'raceMeetings_f6f4cdcd',
  teams: 'teams_f6f4cdcd',
  calendarHeader: 'calendarHeader_f6f4cdcd',
  dateDisplay: 'dateDisplay_f6f4cdcd',
  filters: 'filters_f6f4cdcd',
  loading: 'loading_f6f4cdcd',
  calendarContent: 'calendarContent_f6f4cdcd',
  dayView: 'dayView_f6f4cdcd',
  timeGrid: 'timeGrid_f6f4cdcd',
  hourSlot: 'hourSlot_f6f4cdcd',
  hourLabel: 'hourLabel_f6f4cdcd',
  hourContent: 'hourContent_f6f4cdcd',
  weekView: 'weekView_f6f4cdcd',
  weekGrid: 'weekGrid_f6f4cdcd',
  dayColumn: 'dayColumn_f6f4cdcd',
  dayHeader: 'dayHeader_f6f4cdcd',
  dayName: 'dayName_f6f4cdcd',
  dayNumber: 'dayNumber_f6f4cdcd',
  dayContent: 'dayContent_f6f4cdcd',
  monthView: 'monthView_f6f4cdcd',
  weekDays: 'weekDays_f6f4cdcd',
  weekDay: 'weekDay_f6f4cdcd',
  week: 'week_f6f4cdcd',
  day: 'day_f6f4cdcd',
  otherMonth: 'otherMonth_f6f4cdcd',
  today: 'today_f6f4cdcd',
  meetings: 'meetings_f6f4cdcd',
  meetingRectangle: 'meetingRectangle_f6f4cdcd',
  trackName: 'trackName_f6f4cdcd',
  moreMeetings: 'moreMeetings_f6f4cdcd',
  noMeetings: 'noMeetings_f6f4cdcd',
  meetingsList: 'meetingsList_f6f4cdcd',
  meetingCard: 'meetingCard_f6f4cdcd',
  meetingHeader: 'meetingHeader_f6f4cdcd',
  meetingTitle: 'meetingTitle_f6f4cdcd',
  meetingAuthority: 'meetingAuthority_f6f4cdcd',
  meetingDetails: 'meetingDetails_f6f4cdcd',
  meetingType: 'meetingType_f6f4cdcd',
  meeting: 'meeting_f6f4cdcd',
  meetingTime: 'meetingTime_f6f4cdcd',
  legend: 'legend_f6f4cdcd',
  legendItems: 'legendItems_f6f4cdcd',
  legendItem: 'legendItem_f6f4cdcd',
  legendColor: 'legendColor_f6f4cdcd',
  authorityBadge: 'authorityBadge_f6f4cdcd',
  dark: 'dark_f6f4cdcd'
};

export default styles;
