
require("./RaceMeetings.module.css");
const styles = {
  raceMeetings: 'raceMeetings_a4d5bc1e',
  teams: 'teams_a4d5bc1e',
  calendarHeader: 'calendarHeader_a4d5bc1e',
  dateDisplay: 'dateDisplay_a4d5bc1e',
  filters: 'filters_a4d5bc1e',
  loading: 'loading_a4d5bc1e',
  calendarContent: 'calendarContent_a4d5bc1e',
  dayView: 'dayView_a4d5bc1e',
  timeGrid: 'timeGrid_a4d5bc1e',
  hourSlot: 'hourSlot_a4d5bc1e',
  hourLabel: 'hourLabel_a4d5bc1e',
  hourContent: 'hourContent_a4d5bc1e',
  weekView: 'weekView_a4d5bc1e',
  weekGrid: 'weekGrid_a4d5bc1e',
  dayColumn: 'dayColumn_a4d5bc1e',
  dayHeader: 'dayHeader_a4d5bc1e',
  dayName: 'dayName_a4d5bc1e',
  dayNumber: 'dayNumber_a4d5bc1e',
  dayContent: 'dayContent_a4d5bc1e',
  monthView: 'monthView_a4d5bc1e',
  weekDays: 'weekDays_a4d5bc1e',
  weekDay: 'weekDay_a4d5bc1e',
  week: 'week_a4d5bc1e',
  day: 'day_a4d5bc1e',
  otherMonth: 'otherMonth_a4d5bc1e',
  today: 'today_a4d5bc1e',
  meetings: 'meetings_a4d5bc1e',
  meetingRectangle: 'meetingRectangle_a4d5bc1e',
  trackName: 'trackName_a4d5bc1e',
  moreMeetings: 'moreMeetings_a4d5bc1e',
  noMeetings: 'noMeetings_a4d5bc1e',
  meetingsList: 'meetingsList_a4d5bc1e',
  meetingCard: 'meetingCard_a4d5bc1e',
  meetingHeader: 'meetingHeader_a4d5bc1e',
  meetingTitle: 'meetingTitle_a4d5bc1e',
  meetingAuthority: 'meetingAuthority_a4d5bc1e',
  meetingDetails: 'meetingDetails_a4d5bc1e',
  meetingType: 'meetingType_a4d5bc1e',
  meeting: 'meeting_a4d5bc1e',
  meetingTime: 'meetingTime_a4d5bc1e',
  legend: 'legend_a4d5bc1e',
  legendItems: 'legendItems_a4d5bc1e',
  legendItem: 'legendItem_a4d5bc1e',
  legendColor: 'legendColor_a4d5bc1e',
  authorityBadge: 'authorityBadge_a4d5bc1e',
  dark: 'dark_a4d5bc1e'
};

export default styles;
