
require("./TrackConditions.module.css");
const styles = {
  trackConditions: 'trackConditions_14ad5cdf',
  teams: 'teams_14ad5cdf',
  trackTitle: 'trackTitle_14ad5cdf',
  header: 'header_14ad5cdf',
  timestamp: 'timestamp_14ad5cdf',
  overallCondition: 'overallCondition_14ad5cdf',
  rating: 'rating_14ad5cdf',
  surface: 'surface_14ad5cdf',
  alerts: 'alerts_14ad5cdf',
  alert: 'alert_14ad5cdf',
  metrics: 'metrics_14ad5cdf',
  gauge: 'gauge_14ad5cdf',
  gaugeValue: 'gaugeValue_14ad5cdf',
  gaugeLabel: 'gaugeLabel_14ad5cdf',
  windImpact: 'windImpact_14ad5cdf',
  windLabel: 'windLabel_14ad5cdf',
  windValue: 'windValue_14ad5cdf',
  low: 'low_14ad5cdf',
  medium: 'medium_14ad5cdf',
  high: 'high_14ad5cdf',
  scoreExplanation: 'scoreExplanation_14ad5cdf',
  conditions: 'conditions_14ad5cdf',
  conditionCard: 'conditionCard_14ad5cdf',
  conditionTitle: 'conditionTitle_14ad5cdf',
  conditionData: 'conditionData_14ad5cdf',
  label: 'label_14ad5cdf',
  value: 'value_14ad5cdf',
  recommendations: 'recommendations_14ad5cdf',
  loading: 'loading_14ad5cdf',
  spinner: 'spinner_14ad5cdf',
  spin: 'spin_14ad5cdf',
  error: 'error_14ad5cdf',
  noData: 'noData_14ad5cdf',
  dark: 'dark_14ad5cdf'
};

export default styles;
